### PR TITLE
javascript-101/arrays: add info on second parameter of `.slice()`

### PR DESCRIPTION
**Pull request by arthurvr**
Fixes https://github.com/jquery/learn.jquery.com/issues/611

### CODE REVIEW

**Comment by arthurvr** [comment]
@RedWolves @gnarf @agcolom Somebody who wants to review this?

**Comment by gnarf** [comment]
Can't line comment from mobile, but you can just call .slice with no parameters and get a copy of the array.

**Comment by arthurvr** [comment]
Oh yeah, correct. Fixing it now.

**Comment by gnarf** [comment]
Other than that extra 'required' you snuck in, it looked good to me 😉

**Pull request closed without merging**
