### PR TITLE
change http to https where applicable

### PR DESCRIPTION
**Pull request by OmgImAlexis**
`http://jquerymobile.com/themeroller` redirects to `https://themeroller.jquerymobile.com` so I've updated that.

### CODE REVIEW

**Comment by agcolom** [comment]
@OmgImAlexis Thank you very much for your PR. We do use tabs and not spaces, and it seems that in your PR all our tabs have been replaced by spaces (probably some setting in your text editor?). Could you please change the spaces back to tabs in your PR? Thank you. 
@AurelioDeRosa @kswedberg, apart from the spacing issue, are we happy with the changes? thanks

**Comment by AurelioDeRosa** [comment]
Apart from the spacing, it seems fine. I've tested almost every link updated and they still work.

**Comment by OmgImAlexis** [comment]
@agcolom the main problem not only with this PR but with most of the PRs I've opened and had to close is that the jQuery org doesn't seem to have an editorconfig files in ANY of the repos. If you added that then it wouldn't matter what I used since it'd be changed on save since I have a plugin for editorconfig installed.

For ref: http://editorconfig.org/

**Comment by agcolom** [comment]
@OmgImAlexis Oh,I see. Ok. I'll check with the @jquery/content team how we can best accommodate this.

**Comment by AurelioDeRosa** [comment]
I'll submit a PR to add an `.editorconfig` file today so that we can refine and the merge it.

**Pull request closed without merging**
