### PR TITLE
Fixed 2 broken  links

### PR DESCRIPTION
**Pull request by najela**
I used this [Online Broken Link Checker](http://www.brokenlinkcheck.com/broken-links.php) to recursively check for broken links found at http://learn.jquery.com. The broken links that were returned  are fixed by this commit.

### CODE REVIEW

**Comment by arthurvr** [comment]
Thanks for your pull request. Could you please sign the CLA? http://contribute.jquery.org/CLA/status/?repo=learn.jquery.com&sha=9960e2e4f7b5350889f486ab23a7413f4f35bc1b

**Comment by najela** [comment]
@arthurvr  Thanks for the link. I've signed the CLA

**Comment by arthurvr** [comment]
Yup. Thanks!

**Comment by arschmitz** [comment]
@najela if you would like to help fix broken links and similar issues we actually check this nightly but there is a log of work to be done http://jenkins.jquery.com/view/Websites/

**Comment by najela** [comment]
@arschmitz  Were you talking about the errors here http://jenkins.jquery.com/view/Websites/job/stage.learn.jquery.com/lastBuild/consoleFull?

**Comment by arthurvr** [comment]
Yes we are :)

**Comment by najela** [comment]
Okay. i'll work on those issues ASAP. They're quite a lot though :)

**Comment by arthurvr** [comment]
You rock!

**Pull request closed without merging**
