### PR TITLE
Add method to the JQuery ajax request

### PR DESCRIPTION
**Pull request by MickelSierra85**
I would recommend adding the method to make the ajax request clearer

### CODE REVIEW

**Comment by dmethvin** [comment]
The JSONP transport uses a script tag, so it always performs a GET. Actually showing that in the example may actually confuse things more and make people think other methods like POST are possible when they are not. Perhaps the text could be clarified elsewhere?

**Comment by arthurvr** [comment]
Can you please also take a look at the [CLA error](http://contribute.jquery.org/CLA/status/?repo=learn.jquery.com&sha=ffeb90c7187f1fd296d2bcc80900f53569533e70)? :)

**Comment by MickelSierra85** [comment]
Hi, 
The CLA error should be fixed now.

@dmethvin You are right. I can remove this PR if you think its not needed

**Comment by dmethvin** [comment]
It doesn't look needed to me. I'm not sure how alive YQL is these days either, their forum has gone missing and the last activity on the YQL blog is 2013. In this industry it's hard to find stuff that doesn't break after a few years!

According to the error message (click Details), it looks like the name on the commit still isn't right. you need to change your git info on your computer, see the instructions in Details. If we aren't going to land it though, that's fine. If you see something else that needs fixing and have fixed your git signature, everything should be fine with subsequent commits.

**Pull request closed without merging**
