### PR TITLE
warned users about broken app

### PR DESCRIPTION
**Pull request by githubshrek**
Ideally the app should be updated (the subject of #475), but at least for now we should warn users.

### CODE REVIEW

**Comment by arthurvr** [comment]
@gnarf @agcolom Can I land this PR? It still seems like sorta weird to warn about a broken app instead of fixing it, but seems like the right thing to do atm?

**Comment by gnarf** [comment]
I think we need to rewrite it to not use a broken api, not warn about a broken example -- It doesn't merge clean anyway.

I vote for close without merge and handle #475 ASAP.

**Comment by scottgonzalez** [comment]
If nobody has time to rewrite it now, it may be better to just remove it.

**Comment by arthurvr** [comment]
> If nobody has time to rewrite it now, it may be better to just remove it.

I can agree with that. It needs a total rewrite anyways.

**Pull request closed without merging**
