### PR TITLE
Note what defer.resolve and defer.reject do. Closes gh-693

### PR DESCRIPTION
**Pull request by kswedberg**
Added brief description of defer.resolve and defer.reject. @AurelioDeRosa , do you think this should cover gh-693?

### CODE REVIEW

**Comment by AurelioDeRosa** [comment]
The added sentence is fine and the PR looks good.

I'd also take the chance to slightly clarify the sentence

> If the promise already exists, however, the callback is attached to the existing deferred.

We have two cases in the code:

1. The promise didn't exist
2. The promise existed

In the first case, the promise is created (in the body of `if ( !cachedScriptPromises[ url ] ) {...}`) and then the callback is added. In the second  case, the body of the `if` is skipped but the callback is added anyway. So, what about something like

> If the promise already exists, the callback is attached to the existing deferred; otherwise the promise is firstly created and then the callback is attached.

**Comment by kswedberg** [comment]
@AurelioDeRosa , yeah I like your change. Thanks! I'll update the PR.

**Comment by kswedberg** [comment]
All good now?

**Comment by AurelioDeRosa** [comment]
LGTM

**Comment by kswedberg** [comment]
Closed by d08015a310858e480c746c7e145303be1aba500e

**Pull request closed without merging**
