### PR TITLE
Update dont-repeat-yourself.md

### PR DESCRIPTION
**Pull request by vdzundza**
Added approaches with filter function and ES6 example

### CODE REVIEW

**Comment by scottgonzalez** [comment]
I think we should avoid ES6 on this site. Especially when it's not supported in all browsers.

**Comment by agcolom** [comment]
I agree with @scottgonzalez. I can save this PR for later and label it ES6?

**Comment by scottgonzalez** [comment]
I think it will be quite a while before we'd want ES6 on this site. Long enough that keeping PRs open would be a bad idea.

**Comment by agcolom** [comment]
@scottgonzalez agreed. 
@vdzundza Thank you very much for the PR. We will close it for now, but label it ES6, so that we can revisit it when ES6 is fully supported and feel it should be par of the learn site.

**Pull request closed without merging**
