### PR TITLE
Update key-concepts with XDomainRequest limitation

### PR DESCRIPTION
**Pull request by moo3**
Added this update in order to clarify the understanding implied in the sentence 'This limitation does not apply to scripts that are loaded via jQuery's Ajax methods'. This will help the beginner to understand $.ajax does not work seamlessly with every browser, but only with help of some plugins.

### CODE REVIEW

**Comment by arthurvr** [comment]
Looks like CLA is okay now.

**Comment by RedWolves** [comment]
@dmethvin would you mind doing a quick review?

**Comment by dmethvin** [comment]
It seems a bit vague for the learn site. Something more straightforward would be "Versions of Internet Explorer less than 10 do not support cross-domain AJAX requests." XDR is not really a very good substitute but you could reference it.

**Comment by arthurvr** [comment]
Hey-hey @moo3, still interested in taking this PR? It needs some updating (see comment above)

**Comment by arthurvr** [comment]
ping ping @moo3

**Comment by arthurvr** [comment]
hey @moo3! This is something we'd like to have in, but some updates need to happen. See @dmethvin's comments. Would you mind doing those? Thanks!

**Comment by arthurvr** [comment]
@moo3 Next time, can you leave a comment after making changes? If you don't do that we don't get notified.

@dmethvin Can you give this another review? Thanks.

**Comment by dmethvin** [comment]
LGTM now.

**Comment by arthurvr** [comment]
Alright. I'll merge this one when I get home.

**Pull request merged**
