### PR TITLE
Remove project-specific contribution guidelines

### LINKED ISSUE #554: contribution guidelines not in sync with the rest of jquery
The contribution guidelines (https://github.com/jquery/learn.jquery.com/blob/master/CONTRIBUTING.md) are not in sync with other jquery projects (such as https://github.com/jquery/jquery.com/blob/master/CONTRIBUTING.md) and don't point you towards the overall guidelines (here: http://contribute.jquery.org/).

This means that first-time contributors have no idea how to do things correctly... :-/

### PR DESCRIPTION
**Pull request by arthurvr**
Removes our project-specific `contributing.md` page. These were basically duplicate of the contribute.jquery.org site. Similar to the way other projects are doing it.

Would fix #554. Please don't merge yet, this needs a PR for the theme in `jquery-wp-content` too. There is still a link in the header.

### CODE REVIEW

**Comment by arthurvr** [comment]
PR for the theme: https://github.com/jquery/jquery-wp-content/pull/343

**Comment by scottgonzalez** [comment]
So the team has decided not to have contributing guidelines linked from the top nav? As I said before, fixing #554 has nothing to do with the contributing page on the site. I just want to make sure this isn't being done without forethought. I have followed all of the discussions, but I don't recall a discussion about removing this link.

**Comment by arthurvr** [comment]
> As I said before, fixing #554 has nothing to do with the contributing page on the site.

The current `contributing.md` page is actually the contributing page on the site. The current page is duplicate of the guides on contribute.jquery.org anyways. 

> So the team has decided not to have contributing guidelines linked from the top nav?

Why do we need that link? We would still have a link to the contributing guidelines: http://gyazo.com/6f30f5dab0c82e4ccdffc177776b6fcd, so a second link to slightly different documentation is only more confusing.

We can always bring project-specific guidelines back when we need them, but atm this page doesn't provide any value and only confuses people.

**Comment by scottgonzalez** [comment]
> The current contributing.md page is actually the contributing page on the site. The current page is duplicate of the guides on contribute.jquery.org anyways.

Only because there's a link. They are in fact two separate files with different paths and one just happens to point to the other. Fixing one *does not* require changing the other.

> Why do we need that link?

I didn't say it was needed. I asked if the team had discussed this.

> We can always bring project-specific guidelines back when we need them, but atm this page doesn't provide any value and only confuses people.

But the confusion was something else. There are details in the page about how to actually contribute to the content. I have not reviewed the content to see if all the important information is already covered. This is why I didn't say +1 or -1, but simply asked if this was discussed.

**Comment by arthurvr** [comment]
@agcolom You have any thoughts on this?

> There are details in the page about how to actually contribute to the content. I have not reviewed the content to see if all the important information is already covered.

There is nothing on the contributing page that isn't covered by contribute.jquery.org.

**Comment by agcolom** [comment]
@arthurvr There seems to be info there that is needed and I don't really want us to lose useful info such as everything that is related to adding a new article, which is something specific to the learn site. While I'm all for consistency, I don't see the harm in having project specific contributing guidelines for this site as its nature is somewhat different to the other sites that we have. 
Thoughts? cc: @scottgonzalez

**Comment by arthurvr** [comment]
Yeah, It might be better to limit the project-specific guidelines to topics that aren't the covered on http://contribute.jquery.org/web-sites/ tho. I think I'll update this PR to just remove all guidelines that aren't project-specific, keeping all stuff specific to this site in and linking up contribute.jquery.org at the top. Would that be a better solution?

**Comment by AurelioDeRosa** [comment]
Unfortunately I wasn't part of the whole discussion, so I'm not sure if this PR is still relevant. @agcolom can you recall anything on top of your mind?

**Comment by mgol** [comment]
I'm not sure it's still relevant judging lack of response for almost 2 years. I'll close it then; we can still reopen if it turns out it's still relevant.

**Pull request closed without merging**
