### PR TITLE
Added .editorconfig file

### PR DESCRIPTION
**Pull request by AurelioDeRosa**
`.editorconfig` file taken directly from jQuery's repository.

### CODE REVIEW

**Comment by scottgonzalez** [comment]
See https://github.com/jquery/api.jquery.com/pull/877#issuecomment-174208235.

**Comment by agcolom** [comment]
@kswedberg Could you please have a look? I'm wondering whether we need an entry for each of package.json and *.yml to be set to two spaces?

**Comment by gnarf** [comment]
If that's the spacing we are using for those files (and that is the spacing that npm uses for package.json) I would agree that we should add those to the .editorconfig

**Comment by agcolom** [comment]
@gnarf Thank you very much for checking. @AurelioDeRosa would you be able to add this? Thank you so much!

**Comment by kswedberg** [comment]
So, based on the OP and comments above, I think it might be a bit more "DRY" to do it like this:

```
[*]
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
indent_style = tab

[**.json]
indent_style = space
indent_size = 2

[.*]
indent_style = space
indent_size = 2
```

Thoughts, @AurelioDeRosa , @scottgonzalez , @gnarf, anyone?

**Comment by AurelioDeRosa** [comment]
I think we can combine the second and third sections and use:

```
[*.{json,yml}]
indent_style = space
indent_size = 2
```

**Comment by scottgonzalez** [comment]
I would limit to `package.json` and `*.yml`. Other `.json` files use tabs.

**Comment by AurelioDeRosa** [comment]
Something like?

```
[{package.json,*.yml}]
```

**Comment by gnarf** [comment]
I think it's a lot clearer to just list the stuff twice for that... no reason to like not copy/pasta two lines of indent/size settings...

```
[package.json]
....

[*.yml]
....
```
feels a lot easier to understand at a glance than using the not as well known `{a,b}` glob syntax

**Comment by AurelioDeRosa** [comment]
Fine @gnarf. So I'd say that the final file should be:

```
[*]
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
indent_style = tab

[package.json]
indent_style = space
indent_size = 2

[*.yml]
indent_style = space
indent_size = 2
```

If everyone is happy, I'll make a final PR and then merge.

**Comment by kswedberg** [comment]
LGTM! Thanks for sticking with this, @AurelioDeRosa .

**Comment by AurelioDeRosa** [comment]
File updated. Any further comment @gnarf and @scottgonzalez?

**Comment by gnarf** [comment]
:+1:

**Pull request closed without merging**
