### PR TITLE
Update append-outside-loop.md to use string buffer instead of string concatenation

### PR DESCRIPTION
**Pull request by maschwenk**
From my research, this method is much faster.

### CODE REVIEW

**Comment by maschwenk** [comment]
I have signed CLA

**Comment by scottgonzalez** [comment]
Faster, but not much faster. In 99% of user code the difference will be meaningless, so I'd prefer to keep this out of general recommendations.

**Comment by AurelioDeRosa** [comment]
I'd keep the code as it is as well.

**Comment by arthurvr** [comment]
Thanks for the suggestion, though!

**Comment by maschwenk** [comment]
Sure, no problem. Thanks for review. I was coming off trying to optimize an IE8 string concatenation...where this kind of thing unfortunately matters, but agree that it doesn't belong in these docs.

**Pull request closed without merging**
