### PR TITLE
Update stateful-plugins-with-widget-factory.md for jQuery 1.9+

### PR DESCRIPTION
**Pull request by PxlBuzzard**
I left a note for users of 1.8 and below as well.

### CODE REVIEW

**Comment by PxlBuzzard** [comment]
I have also now signed the CLA.

**Comment by scottgonzalez** [comment]
This is wrong. `_destroy()` should never call `destroy()`.

**Comment by PxlBuzzard** [comment]
Of course it shouldn't, `_destroy` was added in 1.9 to eliminate `destroy()` and the call to its parent. I'll get rid of the instructions for 1.8 and below if you like, but you should be showing how it works in the last three versions.

**Comment by scottgonzalez** [comment]
> I'll get rid of the instructions for 1.8 and below if you like

Yes, please. Especially since it's wrong.

> but you should be showing how it works in the last three versions.

That would be 1.9, 1.10, and 1.11. Though I don't think there's anything special about the number three.

**Comment by PxlBuzzard** [comment]
I'll clarify this here and update my commit.

1.8 and below:

```js
destroy: function() {
	this.element
		.removeClass( "progressbar" )
		.text( "" );

	$.Widget.prototype.destroy.call( this );
}
```

1.9+:

```js
_destroy: function() {
	this.element
		.removeClass( "progressbar" )
		.text( "" );
}
```

**Comment by scottgonzalez** [comment]
Yes, but please don't bother putting the 1.8 code in the article. We shouldn't cater to people on very old, unsupported versions.

**Comment by PxlBuzzard** [comment]
I agree, my original intention was to show the upgrade path but the [upgrade guide](http://jqueryui.com/upgrade-guide/1.9/#added-_destroy-method) takes care of that just fine. If you could reopen the PR, I think/hope Github will automatically grab my latest commit that made the article only cater to 1.9+.

**Comment by scottgonzalez** [comment]
The prose needs to be updated as well. Please make sure you're reading the entire article and not just narrowing in on a single method name change.

**Comment by PxlBuzzard** [comment]
Good point, I should have caught that. The primary change is the last sentence of the paragraph preceding the code example.

**Comment by scottgonzalez** [comment]
Should include an explanation of the fact that `_destroy()` is called by `destroy()`.

**Comment by PxlBuzzard** [comment]
The new last sentence says as much, but I can reword it if you like:

> The base `destroy` method calls `_destroy` on the plugin instance.

**Comment by scottgonzalez** [comment]
Thanks, it's deploying right now.

**Pull request closed without merging**
