### PR TITLE
Change `then(f, f)` to `always(f)` for clarity

### PR DESCRIPTION
**Pull request by evverx**

### CODE REVIEW

**Comment by scottgonzalez** [comment]
Let's not promote jQuery's custom APIs. We should promote standard Promise behavior instead.

**Comment by evverx** [comment]
@scottgonzalez , ok, but what about [`done`](https://github.com/jquery/learn.jquery.com/pull/644/files#diff-08fbf39af46db9e85e5a1c4654132c00L98) and [`fail`](https://github.com/jquery/learn.jquery.com/blame/master/page/code-organization/deferreds/jquery-deferreds.md#L73)?

**Comment by scottgonzalez** [comment]
We should promote standard Promise behavior instead.

There's a ton of content on this site that should be changed, not just related to promises.

**Comment by evverx** [comment]
@scottgonzalez , ok. Thanks.

**Pull request closed without merging**
