### PR TITLE
Comma must be escaped too.

### PR DESCRIPTION
**Pull request by christianrank**

### CODE REVIEW

**Comment by RedWolves** [comment]
Ping @christianrank can you sign our CLA so we can land this? 

@arthurvr you @ mentioned the wrong person here too.

**Comment by christianrank** [comment]
Yes, I've done that now.

**Comment by RedWolves** [comment]
@christianrank I am just now reviewing this in more detail.  I am having trouble trying to figure out the use case that would require a comma to be escaped in this example.  Can you provide one?

**Comment by christianrank** [comment]
I was working on a website where IDs with commas are used,
but i couldn't select them with jQuery, so I searched and found this function and had to escape the comma too.

**Comment by arthurvr** [comment]
> I am just now reviewing this in more detail. I am having trouble trying to figure out the use case that would require a comma to be escaped in this example. Can you provide one?

It does not make that much sense in this example, but people might be picking up the function/regex for 'real' work. If you don't get the point http://jsfiddle.net/zttmccxv/1/ might explain it. The thing is that the comma has a special meaning in css, so must be escaped when passing it to `jQuery()`.

**Pull request closed without merging**
